branches:
  only:
    - master
    - /^greenkeeper/.*$/
  except:
    - /^v\d+\.\d+\.\d+$/
language: node_js
node_js:
  - "11.10.1"
cache:
  directories:
    - '~/.npm'
    - '.jest'
jobs:
  include:
    - stage: test
      script:
        - yarn test:ci
    - stage: deploy
      if: branch = master AND (NOT type = pull_request)
      before_deploy:
        - yarn semantic-release
      deploy:
        provider: heroku
        app: express-jsforce-playground
        api_key:
          secure: doyBbRd59VccHOvwpivCrX9dMq9MhnqKDieEU1Wl6RkkzqkDopLAhz87SOK7SkutZdFxvYdzJjnslouhjCiOACvRxOhBtjiHFUmVChRkpP97pu4shSCqzUTNFl+aKo795SYJ85+MGhrS/gkIth2hCjVtEEomQN7mSS3TUkMSDGuw5XDJw4mHg0U0P3buJOMuv26NV4XFIbd/JiO1g+XW6Xs3W6NeMNy63xTjWxs4aDj52yaxPZDBTLXFneZiVRoOQrSDS1zhYXUyIAPlSWF4oISuF2ORfJTlS8/pUgzq2royqHIrWYx2PLWkzkWpyaMROl1L6dyTtEzSZmuE9QfdA6WY8GTuUD1JuWuFVFz2nwAm62XU7LV7nObDFIuD4Mx/QmI9YpzeHvwV/yai5WwN9d0Xss9PX35R5iiJBPU/gnhFsvAWxvgCttOdELZIpoJv1LK+ttpGuSFj8nxn5cDOgewQxvZCRlnexwyAnCsTojGjiSXAVFpxLsH/mAVr6FlP5ndPCE734ha5tprsbpRZG8l1lJ7oY2YnLbnl2uB6Gv3wPRk5C8T8IXa1ByKySHfspgljwyEJBE11T9+nz0ubM24CpD2B0x0BTbZY4nQLBn2hDBaxV4qQhrRnPP6ouWOu4H6hCiY0SFtOn+4EzY2wd+Kn5/RT/HhG+QPNYrjTCuw=
